// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_FA1Rzm8bHT-r4glyKJ-WvNWUyE54i0',
    appId: '1:874004710608:web:37b3d5a58483f981840ad5',
    messagingSenderId: '874004710608',
    projectId: 'teampulse-4c615',
    authDomain: 'teampulse-4c615.firebaseapp.com',
    storageBucket: 'teampulse-4c615.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgkJwT57OxoXhWQerkZ4kRkKanB8rzumM',
    appId: '1:874004710608:android:96129d1285ae15f6840ad5',
    messagingSenderId: '874004710608',
    projectId: 'teampulse-4c615',
    storageBucket: 'teampulse-4c615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2yEhJqS5GXHsSrdOGpWkJKXVN7KI5WA8',
    appId: '1:874004710608:ios:bc6e766ff620e919840ad5',
    messagingSenderId: '874004710608',
    projectId: 'teampulse-4c615',
    storageBucket: 'teampulse-4c615.firebasestorage.app',
    iosBundleId: 'com.example.teampulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2yEhJqS5GXHsSrdOGpWkJKXVN7KI5WA8',
    appId: '1:874004710608:ios:bc6e766ff620e919840ad5',
    messagingSenderId: '874004710608',
    projectId: 'teampulse-4c615',
    storageBucket: 'teampulse-4c615.firebasestorage.app',
    iosBundleId: 'com.example.teampulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE_FA1Rzm8bHT-r4glyKJ-WvNWUyE54i0',
    appId: '1:874004710608:web:0c904783872b2bec840ad5',
    messagingSenderId: '874004710608',
    projectId: 'teampulse-4c615',
    authDomain: 'teampulse-4c615.firebaseapp.com',
    storageBucket: 'teampulse-4c615.firebasestorage.app',
  );
}
